name: CI PS2

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2dev/ps2dev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add build-base git cmake

      - uses: actions/checkout@v3
      - name: Compile project
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_TOOLCHAIN_FILE=$PS2DEV/ps2sdk/ps2dev.cmake ..
            make clean all

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"


      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: variableIssue-${{ steps.slug.outputs.sha8 }}
          path: build/hello